---
- name: Ensure Minio directory exists
  ansible.builtin.file:
    path: "{{ prometheus_minio_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download MinIO executable
  ansible.builtin.get_url:
    url: "{{ prometheus_minio_download_url }}"
    dest: "{{ prometheus_minio_dir }}/minio"
    owner: root
    group: root
    mode: "0755"
  notify: Restart MinIO

- name: Ensure MinIO service file is on remote
  ansible.builtin.template:
    src: "{{ prometheus_minio_service_template }}"
    dest: /etc/systemd/system/minio.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart MinIO

- name: Ensure MinIO service is enabled and started
  ansible.builtin.systemd:
    name: minio
    state: started
    enabled: true
