---
- name: Ensure Minio directory exists
  ansible.builtin.file:
    path: "{{ prometheus_minio_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download MinIO executable
  ansible.builtin.get_url:
    url: "{{ prometheus_minio_download_url }}"
    dest: "{{ prometheus_minio_dir }}/mimir"
    owner: root
    group: root
    mode: "0755"
  notify: Restart MinIO
