---
# handlers file for prometheus
- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart PVE Exporter
  ansible.builtin.systemd:
    name: pve-exporter
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart Mimir
  ansible.builtin.systemd:
    name: mimir
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart MinIO
  ansible.builtin.systemd:
    name: minio
    state: restarted
    enabled: true
